//! Linux block-device ioctl wrappers.
//!
//! The kernel defines (see `include/uapi/linux/fs.h`):
//! - `BLKGETSIZE64 _IOR(0x12,114,size_t)` — returns device size in bytes
//! - `BLKFLSBUF   _IO(0x12,97)`    — invalidate kernel buffer cache for this device
//! - `BLKRRPART   _IO(0x12,95)`    — re-read the partition table
//! - `BLKROGET    _IO(0x12,94)`    — read the device's read-only flag (int)
//!
//! Each wrapper is an `unsafe fn` generated by the `nix` macros. The safety
//! contract — valid `fd`, valid `*mut` pointer where applicable — is enforced
//! at each call site with a `// SAFETY:` comment.
//!
//! `BLKSSZGET` (`_IO(0x12,104)`, returns logical sector size) is intentionally
//! NOT wrapped here: we hardcode 4 KiB alignment in `aligned.rs::BUF_ALIGN`,
//! which is the universal safe ceiling for every USB block device in the
//! field (most are 512 B logical, advanced-format are 4 KiB). Adding a
//! runtime check via BLKSSZGET would only be useful if we wanted to *relax*
//! the alignment to 512 B on legacy devices, which we have no reason to do —
//! 4 KiB writes work everywhere, and the small over-alignment cost is
//! invisible against the per-chunk syscall overhead.

use nix::{ioctl_none, ioctl_read_bad, request_code_none, request_code_read};

// `_IOR(0x12, 114, size_t)` — note `size_t`, not `u64`.
//
// The size travels in the request number, so the number a 32-bit
// userspace must send differs from a 64-bit one. The kernel supports
// both explicitly (`block/ioctl.c`):
//
// ```c
// #define BLKGETSIZE64_32 _IOR(0x12, 114, int)   /* 0x80041272 */
// case BLKGETSIZE64:      return put_u64(argp, bdev_nr_bytes(bdev));
// case BLKGETSIZE64_32:   return put_u64(argp, bdev_nr_bytes(bdev));
// ```
//
// with the comment "The data is compatible, but the command number is
// different". Both write a `u64`, so only the request code varies.
//
// `ioctl_read!` would derive both the size and the out-parameter type
// from one argument, which cannot express that split. `ioctl_read_bad!`
// with an explicit `request_code_read!` computes the code from
// `size_t` — matching whichever width the target has — while keeping the
// `*mut u64` the kernel actually writes.
//
// Same technique as `BLKROGET` below, though not the same reason:
// `BLKROGET`'s declared encoding disagrees with what it does on every
// target, while this one only disagrees where `size_t` is not eight
// bytes. What they share is that the convenience macro cannot express
// the request the kernel wants.
ioctl_read_bad!(blkgetsize64, request_code_read!(0x12, 114, size_of::<libc::size_t>()), u64);

// _IO(0x12, 95) — takes no argument.
ioctl_none!(blkrrpart, 0x12, 95);

// _IO(0x12, 97) — takes no argument.
ioctl_none!(blkflsbuf, 0x12, 97);

// _IO(0x12, 94) — BLKROGET. Mismatched encoding: the kernel declares it
// `_IO` (no direction/size bits) even though it *writes* an `int` (the
// device's read-only flag, from `bdev_read_only()`) through the argp
// pointer. `ioctl_read!` would build `_IOR(0x12, 94, c_int)`, a request
// number the kernel does not recognise (`ENOTTY`). `ioctl_read_bad!` with
// `request_code_none!` reproduces the kernel's exact `_IO` request code
// while keeping the `*mut c_int` out-parameter signature. This is the
// same quirk documented for BLKSSZGET in `.agents/docs/10-aligned-and-ioctls.md`.
//
// Returns nonzero in the out-param when the device is write-protected
// (hardware RO switch, `blockdev --setro`, forced-RO firmware state).
ioctl_read_bad!(blkroget, request_code_none!(0x12, 94), libc::c_int);

#[cfg(test)]
mod tests {
    use nix::{request_code_none, request_code_read};

    /// The generated request numbers must equal the kernel's.
    ///
    /// These wrappers are macro-generated, so a transposed digit — 95 is
    /// `BLKRRPART`, 96 is `BLKGETSIZE` — produces a perfectly valid
    /// wrapper that asks the kernel to do something else. Nothing else
    /// in the crate would notice: there is no device in a unit test to
    /// return a wrong answer.
    ///
    /// Values computed from `_IO`/`_IOR` in `include/uapi/linux/ioctl.h`
    /// against the declarations in `include/uapi/linux/fs.h`:
    /// `_IO(type, nr)` is `(type << 8) | nr`; `_IOR` additionally sets
    /// the read direction in bits 30-31 and the argument size in bits
    /// 16-29.
    #[test]
    fn request_codes_match_the_kernel_headers() {
        // Compared without a cast: the macros yield the platform's
        // ioctl request type, and narrowing it here would hide exactly
        // the width mismatch the const assertion above guards against.
        // _IO(0x12, 94) — BLKROGET
        assert_eq!(request_code_none!(0x12, 94), 0x0000_125E);
        // _IO(0x12, 95) — BLKRRPART
        assert_eq!(request_code_none!(0x12, 95), 0x0000_125F);
        // _IO(0x12, 97) — BLKFLSBUF
        assert_eq!(request_code_none!(0x12, 97), 0x0000_1261);
        // BLKGETSIZE64 is width-dependent, and the kernel accepts both.
        // What this crate sends, on whatever target it was built for:
        let ours = request_code_read!(0x12, 114, size_of::<libc::size_t>());
        // _IOR(0x12, 114, size_t) with an 8-byte size_t — the native
        // `BLKGETSIZE64` a 64-bit kernel matches.
        assert_eq!(request_code_read!(0x12, 114, 8_usize), 0x8008_1272);
        // _IOR(0x12, 114, int) — the kernel's own `BLKGETSIZE64_32`,
        // which its compat path handles identically.
        assert_eq!(request_code_read!(0x12, 114, 4_usize), 0x8004_1272);
        // Ours must be one of the two the kernel recognises, and the one
        // matching this target's width.
        assert!(
            ours == 0x8008_1272 || ours == 0x8004_1272,
            "encoded request {ours:#x} is neither BLKGETSIZE64 nor BLKGETSIZE64_32"
        );
        assert_eq!(
            ours,
            request_code_read!(0x12, 114, size_of::<usize>()),
            "the request code must track size_t, not a hardcoded width"
        );

        // The neighbours these must not be confused with.
        assert_ne!(request_code_none!(0x12, 95), request_code_none!(0x12, 96));
        assert_ne!(request_code_none!(0x12, 97), request_code_none!(0x12, 104));
    }
}
