//! Linux block-device ioctl wrappers.
//!
//! The kernel defines (see `include/uapi/linux/fs.h`):
//! - `BLKGETSIZE64 _IOR(0x12,114,size_t)` — returns device size in bytes
//! - `BLKFLSBUF   _IO(0x12,97)`    — invalidate kernel buffer cache for this device
//! - `BLKRRPART   _IO(0x12,95)`    — re-read the partition table
//! - `BLKROGET    _IO(0x12,94)`    — read the device's read-only flag (int)
//!
//! Each wrapper is an `unsafe fn` generated by the `nix` macros. The safety
//! contract — valid `fd`, valid `*mut` pointer where applicable — is enforced
//! at each call site with a `// SAFETY:` comment.
//!
//! `BLKSSZGET` (`_IO(0x12,104)`, returns logical sector size) is intentionally
//! NOT wrapped here: we hardcode 4 KiB alignment in `aligned.rs::BUF_ALIGN`,
//! which is the universal safe ceiling for every USB block device in the
//! field (most are 512 B logical, advanced-format are 4 KiB). Adding a
//! runtime check via BLKSSZGET would only be useful if we wanted to *relax*
//! the alignment to 512 B on legacy devices, which we have no reason to do —
//! 4 KiB writes work everywhere, and the small over-alignment cost is
//! invisible against the per-chunk syscall overhead.

use nix::{ioctl_none, ioctl_read, ioctl_read_bad, request_code_none};

// _IOR(0x12, 114, u64) — nix's ioctl_read! handles the _IOR encoding.
ioctl_read!(blkgetsize64, 0x12, 114, u64);

// _IO(0x12, 95) — takes no argument.
ioctl_none!(blkrrpart, 0x12, 95);

// _IO(0x12, 97) — takes no argument.
ioctl_none!(blkflsbuf, 0x12, 97);

// _IO(0x12, 94) — BLKROGET. Mismatched encoding: the kernel declares it
// `_IO` (no direction/size bits) even though it *writes* an `int` (the
// device's read-only flag, from `bdev_read_only()`) through the argp
// pointer. `ioctl_read!` would build `_IOR(0x12, 94, c_int)`, a request
// number the kernel does not recognise (`ENOTTY`). `ioctl_read_bad!` with
// `request_code_none!` reproduces the kernel's exact `_IO` request code
// while keeping the `*mut c_int` out-parameter signature. This is the
// same quirk documented for BLKSSZGET in `.agents/docs/10-aligned-and-ioctls.md`.
//
// Returns nonzero in the out-param when the device is write-protected
// (hardware RO switch, `blockdev --setro`, forced-RO firmware state).
ioctl_read_bad!(blkroget, request_code_none!(0x12, 94), libc::c_int);
